services:
  db:
    image: postgres:16
    container_name: gov_chem_inv_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gov_chem_inv
      POSTGRES_USER: gov_chem_inv
      POSTGRES_PASSWORD: gov_chem_inv
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: gov_chem_inv_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_BASE_URL: http://192.168.0.158:4000
    container_name: gov_chem_inv_web
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  db_data:
